### PR TITLE
Lots of Stuff

### PR DESCRIPTION
**Pull request by oshaboy**
2 new operators, HI and LO to get the high and low bytes of a label. Useful for Self Modifying code. I found myself contributing Chip-8 code to TRSE which uses this assembler internally. And this is needed for some code generation. 

Arithmetic Expressions on immediates. Arithmetic on labels aren't supported yet. Eventually I will get around to it. 

A bunch of cleanup.

### CODE REVIEW

**Comment by oshaboy** [comment]
Hang on I just found a bug

**Comment by oshaboy** [comment]
Yknow I think I will keep this pull on hold until I get arithmetic on labels.

**Comment by oshaboy** [comment]
Yeah I changed so much stuff that I think now it counts as a fork and not a pull request.

Feel free to port whatever. Though I removed the HI and LO because I want to make it part of the arithmetic subsystem.

**Comment by wernsey** [comment]
I actually gave you commit access to my fork, as a way to say thank you for all your efforts.

**Comment by oshaboy** [comment]
Yeah but I kinda took over the assembler.

**Pull request closed without merging**
